import { Icon } from '@iconify/react';

export const dummyData = [
    {
      invoice: 'INV-1',
      property: 'Overseas Retreat',
      amount: '$50,000',
      status: 'Paid',
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: 'INV-2',
      property: 'OceanView',
      amount: '$20,00',
      status: 'Open',
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
     invoice: 'INV-3',
     property: 'Cantebury View',
     amount: '$50,000',
     status: 'Open',
     action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: 'INV-4',
      property: '147 Ocean View',
      amount: '$20,00',
      status: 'Paid',
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: 'INV-5',
      property: 'Downtown View',
      amount: '$50,000',
      status: 'Open',
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: 'INV-6',
      property: '147 Ocean View',
      amount: '$20,00',
      status: 'Paid',
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
        invoice: 'INV-7',
        property: 'Tennessden View',
        amount: '$20,00',
        status: 'Open',
        action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ]
    },
    {
      invoice: 'INV-8',
      property: 'Miasmin View',
      amount: '$80,00',
      status: 'Paid',
      action: [
      {icon: <Icon icon="carbon:view" color="gold" />},
      {icon: <Icon icon="uil:edit" color="green" />},
      {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
   ]
  },
  {
    invoice: 'INV-9',
    property: 'Hotel Continental',
    amount: '$210,00',
    status: 'Open',
    action: [
    {icon: <Icon icon="carbon:view" color="gold" />},
    {icon: <Icon icon="uil:edit" color="green" />},
    {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
 ]
},
  ];


  export const invoices = [
    {
      invoice: 'INV-1',
      property: 'Overseas Retreat',
      amount: '$50,000',
      status: 'Paid',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: 'INV-2',
      property: 'OceanView',
      amount: '$20,00',
      status: 'Open',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
     invoice: 'INV-3',
     property: 'Cantebury View',
     amount: '$50,000',
     status: 'Open',
     unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
     action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: 'INV-4',
      property: '147 Ocean View',
      amount: '$20,00',
      status: 'Paid',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: 'INV-5',
      property: 'Downtown View',
      amount: '$50,000',
      status: 'Open',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: 'INV-6',
      property: '147 Ocean View',
      amount: '$20,00',
      status: 'Paid',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
        invoice: 'INV-7',
        property: 'Tennessden View',
        amount: '$20,00',
        status: 'Open',
        unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
        action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ]
    },
    {
      invoice: 'INV-8',
      property: 'Miasmin View',
      amount: '$80,00',
      status: 'Paid',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
      {icon: <Icon icon="carbon:view" color="gold" />},
      {icon: <Icon icon="uil:edit" color="green" />},
      {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
   ]
  },
  {
    invoice: 'INV-9',
    property: 'Hotel Continental',
    amount: '$210,00',
    status: 'Open',
    unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
    action: [
    {icon: <Icon icon="carbon:view" color="gold" />},
    {icon: <Icon icon="uil:edit" color="green" />},
    {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
 ]
},
  ];

  export const maintiReq = [
    {
      invoice: '1949 Tennessee Avenue	',
      property: 'Electrical Issues',
      maintainer: 'Fred R Burns',
      status: 'InProgress',
      attachment: '_',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: '1949 Tennessee Avenue	',
      property: 'Electrical Issues',
      maintainer: 'Fred R Burns',
      status: 'Complete',
      attachment: '_',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: '1949 Tennessee Avenue	',
      property: 'Electrical Issues',
      maintainer: 'Fred R Burns',
      status: 'InProgress',
      attachment: '_',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: '1949 Tennessee Avenue	',
      property: 'Electrical Issues',
      maintainer: 'Fred R Burns',
      status: 'Paid',
      attachment: '_',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: '1949 Tennessee Avenue	',
      property: 'Electrical Issues',
      maintainer: 'Fred R Burns',
      status: 'Complete',
      attachment: '_',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: '1949 Tennessee Avenue	',
      property: 'Electrical Issues',
      maintainer: 'Fred R Burns',
      status: 'InProgress',
      attachment: '_',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
    {
      invoice: '1949 Tennessee Avenue	',
      property: 'Electrical Issues',
      maintainer: 'Fred R Burns',
      status: 'Paid',
      attachment: '_',
      unit: "Unit 1",
      month: "July 2023",
      end_date: "Aug 2023",
      action: [
        {icon: <Icon icon="carbon:view" color="gold" />},
        {icon: <Icon icon="uil:edit" color="green" />},
        {icon: <Icon icon="material-symbols:delete-outline" color="red" />},
     ] ,
    },
  ];